---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acr-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgAOUOA9eOx2KGZTvSbdceiglfsX2oxp8xQDEXf2L0iLdHn0tezmujHLLfJPkJrSW6Vb+m9QeVxTi9zeI5KJQYVn8CY0AT82nKvaPQAtIfEpmHvLCJbPhkkuc7AA7cefb5ICflzJIc07UK1fbyC0N1bNJ4nw9vG701hkjJ0LYpeBz+wERy1JBZX9D+1iRyygDldQlivQu8gHWZXpg/gnoeU+cxhr1BENuxDWizByBAB5IHa5HqQlf/isX6SP/ryRCI9S43uQ7CaDAxiBFi1ltcii4i/Zsof6/W31bgdJA9Z8me6LRkEpUr8yAJQLgWtxR7idcQUQPjRG7UqyP6RnMn4XOPZQdJAfcCP6QRIypbtNAL/sqguleG7/mYMtOrJWK9sBQ17SeTsAHfTJtNlxne1n6QNPIUU/EcX8OvuG9hdgQQ9GlpH0BRfuYucBROw2ifi8wpGL7WLbyByx3j4+/+3hwcRPKNVRkLQb4JuQodcsA/dJDm+ufgAyk/+ZlDvEcrNdc+tsT5CZXLRjrYaSt6kBCgeG3c7xQbBE4QuRSLKJckIGSBFn26RIDq4/ZyBYCkzAcAWKT//A+Rs7w7gls/q2nt7f5k77cmJo54knA+tqJPBdPR43qZwrJcAPOq1jqVlpzYAB9XLiwLX/RdD8l/li+n/wbDC+VoAig64FVgNozv+/3mI+5yQQxxLEywwC96EPKIP3KzN/fhgYo6Ug/3jtByFTov8z9+MRvakqh5M00Pk5J9Qn0Z88620dvYksyu7Sj1rrhD73nluw2m3KA34MM2erMPzBc3WewC+pLTDkfCJTi2LCh/j7oCXRX6XBe1fpuK6IHXGkYCSm66AFlsm7DxVQsEMDHEZzgWF10uMq54Tac/2UYQbndLAPUpQn9w43qjBvev9ZFb2EVg4KE5Xq4Yzihb+KOsmzHAJst9wux6UuW5j5R3W8sc5+c+B22c41VU+f4ak/LJraHtIIXo/m6lkBEftYU8ntLwW/1B5RHqbBmocnnDXQ4oOUWW9ANJCmgOlF8wXiyJC3HTCxm+MfA3LKtssKqOG5T0ZNxpxdwOaizEkTgXPkjuBe2Tc71vFhnrp3P8jFvIHE0Q==
  template:
    metadata:
      name: acr-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
