---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: dev
spec:
  encryptedData:
    DB_PASS: AgACvrB3W29MxjZGa+Jtb5+oVghrOIIK4th7Upbb1jFiV+WC/88CgDGu28cqoY3ElYYFke8Fh54cJlzvJU3aQjVGxYjJKbBNlFT+Zroy2ExqZjzp/m8/ksjrIAqeHDEq8r8BdEMyKSbL48A3b6j5sIJpLih2QURdysy97D0IsGXxaRrNcasksF3m373KPwZ0kbCI7/s/e5LoqQpnayTdteXcUbg8PPX69sVeXG7oMui/lEv3TDgFr71VOWB8lDEhcd2zgzyfH1mLfRjliM1k2AXJj8CpQFcjB1nRFdKK42pe9pON6RozQsscEHuQiQ2U3SNg38Rcpi2aRirqmNXYueu7Bcs9vQx4WQRdEirZVcIDC7zer81pqh/lLyvvS/tuK435IFO2DL7D8vr8AKqW21RISo6U5+Eqf7mbr6hnaWnf/DxSuvWeeL7z2L2eWfcj3Z6tSKzQaHGOeRF9fdWiJSVRKXhxuCnG9+VgcN5HELYLpcpX9kmRURkHo2e+CRJ0NwGRj0h5OpMJ6DDYTxFFs6xXMeLo3uf7HnQ54+WZDucewhAanf4u5TnqL4ZmKwaoLdCT5TDMjudh2i865lViOiPElb7Cu6eFfYBhoDrs8I+APJE3qUSzShnb+iNWLSp1DiBpivYcB5l7kNSHiNSKZ+T9TYAAuzMn+SuKLeNOCeMw3a2yDbnCa1ZpfQMMp878gYeSxBgQKwPaWSyMvQ==
    SECRET_KEY: AgAtaXtuklzsudHlmTCXR2rHltZqU50shtGPjQ74EDIthdNrcymTj8qLrxb3aAgWTaZB7tAJcZcUvaQwPMUW+WNaEfctDBNHeVDwX65ktmE5bnc4RKa3mK4QN05Fl3CSwvZ0/8jCygAs7i2kBl8xP/a31ni7zr7Hyv7XE7ItT4W3r6y9ZNpO18MnkqEUH4MqJFkkF2uXGXvqTpNw/ivIX++g+Inusqj8YjJqH94L2WXAtUco61MehREN0ba15mIiTjsd3RgmA7r2+6y0Nli9UeO5OS1pF6Wv4jlPBhpZFsKaTNOMMErFmkxou5BPqqkusqrnEWUtatUTAX0mKkf11WRWb/S+x8VDX39bOrNFZDLGtE4/4lME5YaBLQhgVKxOTqj316RAv4sZxrON/s0hyyK03yb6nUqSHaTRxIDnrSwKnoMPXhVlGsyMJXOK3VhjVfQ3CSUcfNgKmpnRsOJhp+IBFtTB7QcORuIHcHroB2v8Gqq0mTxewU2Sht4TOOc6qikyzwF2sznKKDdzJi6VlA3MNtpNt+76YfDwaay5KmmHEmzQi0ch+EylxpyHkmU68JJCY1KQjDzmMsCxS2d8PDxop91ROk7KW4z5M0+xhpwOzqTX8ZUh0bbHKW/ozW5/ihLVolmdEUKEEeXNPdzq7Of3pJs5OyqG5sznrUoTQnK9cWh3pEE99l4+ZOQkYZW0cvt9CbSegWAQ5YqfGrwXLrQUdD1yYsx4rYbh
  template:
    metadata:
      name: backend-secret
      namespace: dev
