---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: dev
spec:
  encryptedData:
    postgres-password: AgAxlT0MWvjg8sdIhsW7ItzPin7h/VFqAdFefQD+BFTpST3MV94t9EBne9DSQCENRncnTqzjfHbGb5jFGCr54Pf+eIfyBOe/nPHnP+Thq3+Uq9BZ0UhAHrv35OCkxxpuDOMX8wihSsFuAxzLk2ef52PM7wjp5HEA9sqZiTq5SAkWsJfwWZp3vp3pT+WkDKrqs03bouSYxk0rnjtuMGj5iLO6myZkndj2cJrHrO3qnF44o76aOz2mWswG15I4jrM8YXcwzpVHpxpwTdyOACHa2o/r6f/rlDaR+ZOCzU1jktORcsyl8GACZ/vn7Pb0VFU+vWlXUnyXMi5M/r4jFl6ommRQk3rVVYXDvshV6/6bEk9bBH+p9pEuoLncyjjLLMfrTBHA98sKIu6QG+4QugzfrM/LaqHuN+IjSV7oF4zW+wIwm+VU+KwBbs8etP/lmB9G0mFhvg61Ycsj7Y/6KiVvebaPLJZk4bhWHcQGWCddvY2BMuX8JoA/78NJjbK64vNK/39ZUjogkRlkn+bte88S/gokvj4x+MAOkRip+0PgTmF+vRuV1/rXmsxJ2lTCKOJW04dgu+gP/iJ/vti4y64gBKqhUHsx5Z2ZzhdY0MLI9cj1psI/5AqQtxT4e+L7PKMXgAsdQ+hsXZWiEPKSEm5keoW7yGqy6141GRiKdn9PftRV8jMuZTy7W9AbhBEDEbHpYxL2AlE43DVD5h0CBQ==
  template:
    metadata:
      name: postgres-secret
      namespace: dev
