---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acr-secret
  namespace: prod
spec:
  encryptedData:
    .dockerconfigjson: AgDGneWDTpdu9KCIakQINMyoOfy/ChF5gm2cmYa0jBGtgDp7BymXLPwm8HBlrKFWaBvCD4jPXRLprMjy+AX3xl0i+fNzb+M4HxZkrHHtvCH8yth6XET+kbP1YjagzPQPg3CKFYrneYt3xXOWfPtgvI3miReTA3ODYwbfd5M2VnZkDpj3qQTbO6vJv6q/+kzBXi1WNwwT6I6aF85Ir2RNdIn2g+mA+YM9MWNLOKVE08mm/hw8H3qeO/isuEvkUk7AIMD+EfbM9JqMJvYk8CjeTJRiydSnK+JZhV/GP6fCahwnaAS3H9dLqo5wrJECeYLiY2GFLhKJ6W7JwuUyR6Fc3J0N5Il4A7TSo1IeLRSe0RqNHpA8SIkl9xlXu9n3BNU92gPUTgD+cLlaOcSNSVkKt1/FU2lw2ZVNBzBEnGk9PRTG29Nty1JT+ywkgv0zcFBPkClQ3WgIJq/xDCY5vGeH6b57TvUqOFIH0oupi2C5B35ShLf5ItuQV05Oz+jjMYp3z+7myrwCUA3nfdRiaJtMg4dEqNBAcfNk0OOnTy4Xr5/ciz3xG2e3P5D711tjL9EVagQLci7QXTAtU+y7uZgbTC9JB9iOvC6a04r574+F+m7tQ4eRWzo+oJEHXh/BidLG9a/ot3qFXBYy5tqzK4o98Jw+04VqwgJt7Tca3O32W9oR8VwXoqwm0+GpFPVyHgZiIkhsjJIsAI1sBtEqkjBjmlQpNWwnFbC4Ul1tXwaURRxWBuwN33Lm5PelN8jIv1N0h3HrIqICnr0yR8kf1NEMC6+yG42v22J/kfYSXtwNNNUsUI32rz9Cizlx0djXjcZ8DoIJGh7lt0z8yodYKbybgPMDeeTzDenYd/lG/0JPYjpm5FXKMOz96oSVEVlyY8GMmYodeRf6dKrgNbKBaC2PO5Y9PaDD8J4AyUaiES9xoxQZBzBw80+c8Ew5zTaXLA1YnLMba9VM0MvOq4RkGZyNJtRlUcTu+bdRQGjsHl3QhfzhBR3q8tuqvXll9egLF0Wtdk8R0loGBbQirF/7dVWB3dex2Kp4DXG+HL/TzQEl2iAcDrFY+gOJiwUEpd/eSekQlVzVHGHKBEWxf/p35g==
  template:
    metadata:
      name: acr-secret
      namespace: prod
    type: kubernetes.io/dockerconfigjson
