---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: prod
spec:
  encryptedData:
    DB_PASS: AgCtx+516MBjo1kdvha47iKQn8PobZlYrJTNRUt0v+E7k9uRHI1EEDi9VMgPg1vT135pi8a7ZxOpepJ8PBznbmznhESpXRshBOdQJyddGA6tTvVIp/jEW8LJx7nbIc1zQ4ixHxrSsagR4CtUD+odbzNsgUR4wFyPKNJtQoAkwtB1zFhD6EsG/VU5LU0v//OZXfU3FO7WDOyfcuyr4/jNK8qekznY2VDoJshFi27F686w4mzJ9dUO3QD8NNPDcKgrXhtolV+RmGCWyBJuIaP8q6LRCN4W0ZWmFnhg4xel33KVb36PoHo8lgH7fmSin4blp2gwAdJ9gE8FRLla0WrsEwlnXfTZ4nmB+kz/M+t2KQlw2OesM8Ed8pdVGlUx+5HRMtPMImvnKVUjI2hh+qGvCYbLnFg5a5K9XccGJIkP6Zv3ev8sZIiEjFDgu3l6xwcW17YYXfQANz+JussQgvcLIa1qy9M24cCLQT7/HCjW6jq8YWBbdkalnWXuVxnmgiZm9SNuUI5TteUgmjVnuHvRo/vgvFB1PNBkV7T1CaJW+bQPOi1C00G+LPmM/TkUtVa+sJ6S4VNTU36uHbqION5+jTtAebhkPepT5vcibMv7izXKSUp5HHeim2Nj3+gKJLbfNn4m4musGDxD2lIZddBytgO7WoA+Rn0eFsTaGDFDqB7IEwfbW5q7UTYyaXVsb5m7aq4nLnGmRHR8W2jJ5A==
    SECRET_KEY: AgBbafAlrccSo+1PgkBJBDGEPdGJBeGTg994rprNYLYHA7DUd6hOBNUhySAGRDDKOXlOr5BzDvsKrMOrXQLUvdtOFejCU3ppABZUSLbCo1hGsSjlvUkvk5QFHbIkxmeyJK3mVU1x1VI0maRthD10i4n2ee/o3aysdUnS15lEqmgV8U7V1eVbn5crrmotDibPhuYch7oIPVJMJYJNRRp7oIWi7dDAv249Q0RxNGCL6oD4PDCYzQhwqlMY7K+nfUJ/s1X2hPJNE3+bk6AK65gAvxENlL1r5D1EZZgX6pNGyiRTWrg6XY2VfGAkBPCjUjq50lISSDTqdxrjtdq5GcAfc3MOnAbEuEUUpRSPOGZiy075GXEzHupDuI9YbyvQ+7FlE0RfxPP3wnFCXKR5uS3eirXzIBZWJud9s7zzcSQXDxy4Zkek7paHFmjiIAPB9DAW0kiQEF2K6HoYyK+ssH9R+WprQzP4mQz8dxeppep2gMeET0xUiRvCPJRwJgDGwSr3+9JAVprQGAUejt8iJreYKz9VphYh5DlV8F49dpVCgrJzKaVcKjkmQ4hUInlnG4q86ntlM/I0DC2RKRfoz4OJwYqRqZfGOJEjuKzS3mU7Fb6NjNmBk+D+jQopGi11qmJzVfNFPMTJSlSxkdo4tsvX0AFNdJXrcSFIMR/QOhOVfk7yMMvPzaqgiXaUA1nVJO4J69iNY1xpd9FzJg+/ikk1t83hMDa/ByXtkiVY
  template:
    metadata:
      name: backend-secret
      namespace: prod
