---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: prod
spec:
  encryptedData:
    postgres-password: AgAbxV9U98CjG2QLcfXDFktWh1vKgZW2+ugNG9aQ1RYeN8HEBgKzXx3YMI246n6nDBTItUF2zqthxvbb8RL/mPhGgvh2ofDn0N9kVtrdZvR4YEimfVkzyctb9sdT3V/3bBeD8uRUxbsB3WkHzZuwxmsFv9P215WM+dj/kOlwGEXt0EQz7446NMpVc6EUeWzLurYb2jkVsxjSMxGP0RKf1L84ZgqQYjTpi+QqMPqwDGMRwZRm1LHkuWvm7uF84h1yYHkbFQRKsKl2MryirizA6IabE64DFbfHOOkcrB2LU1pvAvB/GhE+2x+eWraespzeOSYQPWNwapDJhu2AFdW3VRYAE2ocCeL6v4C0BhFO0xhQEdZGlFRCwBxj3iXRqjtiLVdqvuAIYs4MN50wKTXO6H7/R94le3AkGACDPIZ21oSupcujUa0/wK2abqZkbKvdnr32pfaEzcZiuM5Q3tR2ucE9A9Io98V+NArYgOp0x3Xu9yk/TNUP5T2NNfmIyK5XBnGng01VFH8Vv1SFg+pE5BpqNDgkVISsv1FTyBDZAmkDR26XuJ1gqvYqX4r0FyZ+dcyDl0oseCUQ+OQ6QCejR/ZSmeUTGd8AJvcVpVBTDrigPDCIXWJp027hSjIbvtWDGOfWACftWghp3ON1b7fjGjRspP/mthIvbrBYcvP8SHjd9jPLdFbtvnTK+Nsr8jyJUQ/7Sx0lfeOrFe22ng==
  template:
    metadata:
      name: postgres-secret
      namespace: prod
