---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acr-secret
  namespace: staging
spec:
  encryptedData:
    .dockerconfigjson: AgBd/5XKWTNkte+6fR9o0CmePXQHNmQap7sfTvGQe3x8ipQrp3QQ21rYD/Op4mbPk0YyioxyBjjMEqFCgtkpO/04qvtE3xsCEyP+YgwCNVyFlSah8jptIxdQZT0Ghmgxo++kvSMeuQMDRUGqbQLS4DA9Zdh3KYRow/NbV8WdSwAngUVfswWNF0WMrXL2cka6JwZSmJo3/39Mb+spBAtvJ6DWF/7AWll9oi1TY2hhfzRG8aCLFrwQwHWlV735WF3NVfiePYtbQySzb/86ulqWnU3xhTWPLFSiq2VCSdzTewCFIpJCYIGB8/rxDtP/k8ZQTHTf8aNRxuQsUYE1uL1ASB+j9hQCcBtGEjC1h90NzEgh/Cc1gZDW5jBPue82jZ9QhOVChpP1nXvKyPHY6sp8GWY+KuZdqjUncHsZONVMDazyb83m3cawK7My4aCBJq7bqbK+lyNrAKHymvY+LGo3AIiToBZw/vUvvnBTOFqKHVa8xpizZPmRqN7SoXdccUIXEH18YnL0/F+h/N4eSEI7ABoTUwVC33vPr3YEgchLDxE0ZQ9+XG2EZFCmNdSuSrpfhThpgVwKMUT7K/jcCWYgwwYDwDdHc3E9w3goW1JHulK8J9amrjatdJ/G2D8njSheVBE7sFAXRlBrZZTtSWfYgZPpn/ph6akLF+yncSY9/NA6PsPt74R5ldiEtgm+CpnYRC8Dk2Wuko7XWayjl88hjAGGG+MtEcimLOW2SNDPVpBE9V8b6RKOlHLT+yC1yzJRqb6S1j2uxU2VJ/cgNDl5gvWv2thvuy9VohUpJ7+sC+d6HrmZBDElaF2A0rrI2ppDx8ngEJuPdEydISQMvgN/tDZS8WLjOJJHTGs9y2gtGBtGW/L+VG0vQJKBoXc44Oxy8lneuwpgkeEAqBq9RkzW5LeFEy+o9qCIBIdQvo34+rtwuoVAXqy3Yw8wij9YFNXVCT08+8gwNL1H0SZFBCGVX0GIqlakokinKu0HLRDENVUigRyPVywPebaZjc+1yXjGk3y60LFxaZ31bQUOf3H74H6vOY2PLLBeOxFVedSSa3Lti30ksY3tOFhQsV0vS4bJZKeNoL+F+yGqNsANRQ==
  template:
    metadata:
      name: acr-secret
      namespace: staging
    type: kubernetes.io/dockerconfigjson
