---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: staging
spec:
  encryptedData:
    DB_PASS: AgDm08IebNFnnKZBBKDpr1SDEL7cTsw+ErN44zHKE2kKfWck4Q7NdpshAb+OsS0w3EoVHzPHCs6h6aA+JIM8mLPl0NYScDSuPPY06uK476p+oQDuGFTPF8dYaCV76ICelgrEuvCdaQAgFoH3CLG8xGz4V6P1eTw0JIpwYekTIHH5KhWMBv37DOBj6T+PPly2iajPoECQs76m2lkxZ2fkiurvMX/tRLfzdwkZf+fALNn4DXIyH81WTL7W78Mx7cRWjS6pDS6QCOqrrHe8HalWEGyhsmjLPRmbeIrwRbUQHxArtwfsNX3axZqaGbNG3CZDuhBcrV791bpig18OIx5D2HN4BOnYuAknLwrbnVVKA5OoivsCFaFdMgo9WvZGOzk9qbW645Kng1eW1wkxrtPvBsb/6x3VU5D0ooXtAiWjO+FyysCOTZQUosiL3FVShi50Z4Ln19gl6nkV3Tf217JfLpFKggi0wj8I9HIaoXOPb5Bf5oOWRfeJarteMlvHb5ZgIxPM+1KSGeFKVnhFvfrAMvLsa6VKTULtDj1zAqKzzVs2op00vNYuTfEz7ktkjICirlFyypI0+oWEdDu7qPWOofQ/8Gvw/vcrk2jrgdbemZhMdv6FvmUATlaP23ltKABGbeKFt9nTAKcv+5DCcTgqOGMAluWH7iCgd57qVRO97J2txr7Rs0dFOGZoU+gXgC4QzZRlK5LXtsnXkiXM8A==
    SECRET_KEY: AgDyJisBvL14fND9n7Q0AE4alkDNDzQpzoC/7wt/hgh66qXnKrWsV6JYYGhdwnXo6mMgZSudLEyZbXBMAP1dYkkzC/hevzMDaRWRFesIUpCAohxPU1VnMYfivfvivlfsimlItOuepOuDDL4DLIkcndXeKuUksVBrXh9qFYS+TloaEpvUhe1GHgXZhR8uioVytNgDHUugteyGLrIFxhTLvx49OPlFBwFgpHn+NXDsZPwRdgcEy0F+14c6AFo2TroxSNVqOeHG5srQulOC30C3PqXVfobn+d6fQDVWKHK0NidYLRQrhyfErcmtTJe9l6ETdDzugH1tdnq+BWGq1zZowBBud1IQtO5m3SF6nIUUThh8xv5O3VYrEC4SLuLyfyFHtsjT4fbExZ+eMUdFqfgHZ0Pqq+U9rwJhAoMBeD0aYIDZoO6RldcTQ/MlWGk7iE2x58DldXFmqUtz7jVaPIfwaiZQ9kzRk0mEQbgTbG3N+zb9c3bf0hJDDCP4yV0GAad8c/v/80nToIJRKbLzNt0n+NUx7bvNxZbosqQANO13hYmVoGzug0YRBl3wby0vMSoQ4gNeSKK6BuZMqJt5ix2OlbM7aVM5Y0JE5qBnBHhVUIWBIUoWFEM/fGwpecBhEE9/AHPretqGH1yBsMkKw5Cqe+GVLOFR8Zx3lFirI4uAAE92mtv0bcVjUNNlUW6bh6dffYVmGmHdxmscABWLk17nypQ3XgwwfFiQmM8b
  template:
    metadata:
      name: backend-secret
      namespace: staging
