---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: staging
spec:
  encryptedData:
    postgres-password: AgDi6sFStKAKeXQ5r8D5vJ+RuiMm7mDZJU1n6snoH6G5bTj04tLLTSPQhfJtUExCbkx6zXU1lIkvVAOSR4vY9TRfWnfTU7VF+hlfDzNcIkqfez5k9tagtSafaiZ1Fd5ULu3pBnHzAFN242GdcBpVdpnlSx6sKVKlwHwAIhbyubm7DywXFRcwqpV6/jKbifZiP08nBbaeTYRCbX1zcw6hh8WicYjMa7czbvk0oGzzXV5YnZ6sIHHbFUMqsxrLT3N5X4257hThsuCGZTggS0jBQCm7MGLk32EUNnThPG+vm6dVuf3SqCbretyAQrQqjgMLNCRS5oLsNe++A4y7SXJC4dPUwGZTQphsxQwe4ZOJnY8zuzcYX48GHVDtV8Vq6lG4OBEWTxN+BMxvaN9YkgjCW10RlAfb40gqItIHLKnDib3abeAtFcSGxBFU24l5jAH2xnkIF0xYLiyTUF6+tznbGqpaFRs6ltBBXbpg5621dam6N7jFtz+Qhl1BQwe7stvnd3zyvNlE7IhqCm7UPwm3q4FSAJYGxz20IPr7nbAOfPhl60WyA0FELMWUeOwfY6Dlzfhqet6HyD5o4RxcyvRcy/LSjsOg1bBb9Ymv5fpwj11JhfZRiQu9tYcEtdxkwmJvoLjGLwLnqcHGHYf63ZmME+Yffd25mTUzKGxqk4rJazqRiLoI/YRIz8cf7ecRfUnrHGywc7/BKEPLebT0FA==
  template:
    metadata:
      name: postgres-secret
      namespace: staging
