# STAGE 1
FROM node:24-alpine AS builder

# Set Working Directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install Deps
RUN npm ci --frozen-lockfile

# Copy source code
COPY . .

ENV VITE_API_URL=/api

# Build App
RUN npm run build

# STAGE 2
FROM nginx:1.30-alpine
RUN apk upgrade --no-cache libxml2

# Configure nginx
COPY nginx.conf /etc/nginx/templates/default.conf.template

# Expose default env vars — overridden per environment
ENV BACKEND_HOST=localhost
ENV BACKEND_PORT=5000

# Copy built assets from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80
